version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mResvXDs9Gk89Ef